version: "3.0"

services:
    mfs:
      build:
        context: .  
      image: rufusmbugua/laravel
      container_name: mfs_lab
      ports:
        - 1080:80
      links:
        - db
        - adminer
      depends_on:
        - db
        - adminer
      
      volumes:
        - /private/var/www/mfs-lab:/var/www/html
      
    
    db:
      image: mysql
      container_name: db_m
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: mfs

    adminer:
      image: adminer
      container_name: adminer_m
      restart: always
      ports:
        - 90:8080
 
